language: rust
rust:
  - 1.24.1
  - stable
  - beta
  - nightly
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc
  - if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then
    cargo +nightly generate-lockfile -Z minimal-versions;
    cargo build --verbose;
    cargo test --verbose;
    fi
